### ISSUE TITLE
Is data-id  really required?   *And a tiny script to auto id.

### ISSUE THREAD

**Issue by ryh** [razorjack/quicksand#103]
Is data-id  really required? Following is how to use script to ID the data element

``` javascript
  var autoID=1;
   $("ul#work-list li").each(function(){
    autoID++;
    autoIDStr="worklist"+autoID;
    $(this).attr("data-id",autoIDStr);
  });
```

But is there a feature for us do not care about data-id ?

**Comment by razorjack** [comment]
You need to provide `data-id` in to give each iterm an _identity_. This is how Quicksand recognizes the same items in source and destination collections and moves them around instead of fading in/out.

`data-type` attribute is used as a helper to filter the results. `data-id` is what you're looking for, Quicksand will not work without this attribute (or any other attribute that provides an identity to an item). If you're retrieving the items from the database, the database primary key is a good value for item ID.
