### ISSUE TITLE
Changing filters to a select drop down

### ISSUE THREAD

**Issue by knolan2** [razorjack/quicksand#128]
Hi it is not so much an issue but I need help. I want the filters to change to a select menu when the size of the screen changes to smaller size. I used jQuery to append a select tag to the nav. It works! But I can't get the filter functionality to work. I don't know what to put in this function to make the filters work:

$(".anchor-tags select").change(function() {

});

Thank you

**Comment by razorjack** [comment]
Quicksand is an animation-only library, if you can't get dropdown select to work, it's more of a jQuery issue, not quicksand issue :)

My guess here is that if you use `$(".anchor-tags select").change` and then append the dropdown select to your page, the `change` event will not be triggered because the dropdown was not yet present in your markup when you attached your event. You either need to do something like `$(document).on("change", ".anchor-tags select", function() { "..." })` to make sure events are triggered even if you append the dropdown later or use your devtools to inspect your dropdown and and verify if your event handlers are attached.
