### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: [object Object]

### ISSUE THREAD

**Issue by sstyle** [razorjack/quicksand#131]
Uncaught Error: Syntax error, unrecognized expression: [object Object]:checked  jquery-2.1.4.min.js

Try to use this example: http://razorjack.net/quicksand/demos/one-set-clone.html

**Comment by x16** [comment]
Maybe its because of this fragment of code:
`...
if ($($filterType+':checked').val() == 'all') 
{
    var $filteredData = $data.find('li');
}
else
{
    var $filteredData = $data.find('li[data-type=' + $($filterType+":checked").val() + ']');
}
...`

$filterType+':checked' i.e. "jQuery Object PLUS (concatenate with) String"

I got this error too. Just add two more variables with query strings:
`
// bind radiobuttons in the form
  var fTypeSelector = '#filter input[name="type"]',
        fSortSelector = '#filter input[name="sort"]';
  var $filterType = $(fTypeSelector);
  var $filterSort = $(fSortSelector);
`
and use them instead of $filterType or other similar cases of concatenating with strings.

**Comment by razorjack** [comment]
I just released v1.5, compatible with jQuery 2.0+ and 3.0+. The docs are also updated so if you copy the new code from the example, it should no longer throw this error.
