### ISSUE TITLE
Reread the items dimensions

### ISSUE THREAD

**Issue by titel** [razorjack/quicksand#51]
Hi there,

I'm trying (without much success) to make QuickSand reread the items dimensions.

I have an example in which the items initially have one class that gives them one dimension, but, after a class change, they have a different dimensions. However, after the class change, when I run QuickSand again the items are being animated into their initial dimensions. 

Is it possible to 'force' QuickSand reread these dimensions? Or, if this feature is not yet included in the plugin, is there any way I could hack together such an behavior?

Thank you in advance for your support and keep up the good work developing such awesome plugins,
Constantin TOVISI

**Comment by razorjack** [comment]
Not sure if it's helpful after so many years but here's how I would approach it: first, filter and sort the items. The items should be stored in a variable. Then, using jQuery, add the dimension-changing class to the items _in the variable_. Then call Quicksand with the altered items. Quicksand will try to virtually insert the new items to the collection to try to “simulate” the way they'd look like in the end so that it can compute the animation. I think this approach should work :)
