### ISSUE TITLE
Feature request: empty result set messages

### ISSUE THREAD

**Issue by chrismendis** [razorjack/quicksand#6]
It would be great if we could specify an HTML snippet (chosen, perhaps, using a jQuery selector call) that gets shown if Quicksand returns an empty result set.

**Comment by razorjack** [comment]
Not sure if my response is useful after so many years, but Quicksand is an animation-only library and it doesn't force anything else. It animates transformation from collection A to collection B, nothing more. It doesn't interfere with your showing that the result set is empty – just make sure to call your code instead of Quicksand if you detect that the filtered collection is empty.
