### ISSUE TITLE
Change fade in animation origin

### ISSUE THREAD

**Issue by sparias** [razorjack/quicksand#65]
Actually the fade in effect when sorting elements is originated in the [middle,center] coordinates, i would like to make the new elements to fade in from the top, is this easy to implement? thanks

**Comment by razorjack** [comment]
I'm afraid it's not possible due to the way Quicksand is implemented. It's very simple yet inflexible: the plugin simulates what would destination collection would look like in the container and then fades the elements in from their destination position. Doing it in any other way would greatly increase the complexity of the plugin, sorry :(
